FROM public.ecr.aws/lambda/ruby:latest-arm64

COPY app.rb Gemfile encode.sh ./
COPY arm64/ffmpeg /opt/bin/
COPY arm64/ffprobe /opt/bin/

ENV GEM_HOME=${LAMBDA_TASK_ROOT}
RUN bundle install

# Command can be overwritten by providing a different command in the template directly.
CMD ["app.lambda_handler"]